version: '3.8'

services:
  app:
    build: .
    container_name: laravel_technofit
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file:
      - .env
    networks:
      - laravel_network_technofit
    depends_on:
      mysql:
        condition: service_healthy
    command: bash -c "composer install && docker-php-entrypoint php -d variables_order=EGPCS /var/www/app/artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000
    ports:
      - "8081:8081"
    tty: true
    stdin_open: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_DATABASE=teste_technofit
      - DB_USERNAME=postgres
      - DB_PASSWORD='123456789'


  composer:
    image: composer:latest
    container_name: composer_technofit
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel_network_technofit
    command: composer install

  octane:
    build: .
    container_name: octane_technofit
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file:
      - .env
    depends_on:
      app:
        condition: service_started
    entrypoint: ["php", "artisan", "octane:frankenphp", "--host=0.0.0.0", "--port=8001"]
    ports:
      - "8001:8001"
    networks:
      - laravel_network_technofit

volumes:
  mysql_technofit_data:

networks:
  laravel_network_technofit: